###Autenticacion 

###Registro de Usuario
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Eugene Wu",
  "email": "eugenewu@unah.hn",
  "phone": "11223344",
  "role": "client"
}

###Inicio de Sesión
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "user":"emendeza@unah.hn",
  "password":".xf<.tE.q7UC"
}

###Actualizar Contraseña
PATCH http://localhost:3000/api/auth/set-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE1OTk4ZGQ1LTRlZjItNDU4Ni1hYWQyLTcxNTU2MDhkOTBmOCIsInBhc3N3b3JkX2hhc2giOiIkMmIkMTAkdHViOUF2cmxVcVJNL2xQTzVJNE8uLnVGNFRRbjRIbVBKZzhIVkY2WWRnZ0JIWVY5M04ubmEiLCJtdXN0Q2hhbmdlUGFzc3dvcmQiOnRydWUsImlhdCI6MTc1MzkwODcwMSwiZXhwIjoxNzUzOTEyMzAxfQ.IUk6t93l1a1NgmJMX82hVw20InNcb91VozTLMo7k2MU

{ 
 "old_password":".xf<.tE.q7UC",
 "new_password":"ErickMendez123#", 
 "confirm_password": "ErickMendez123#"
}

###Servicios 

### Consulta de todos los servicios
GET http://localhost:3000/servicios

### Consulta de servicios disponibles
GET http://localhost:3000/servicios/disponibilidad?available=true

### Crear un servicio
POST http://localhost:3000/servicios
Content-Type: application/json

{
  "nombre": "Consulta General",
  "descripcion": "Servicio de consulta medica general",
  "duracion": 30,
  "precio": 500.00,
  "disponible": true
}

### Actualizar un servicio
PUT http://localhost:3000/servicios/c8fd3bdd-a690-4a9c-90ae-671563cd84d0
Content-Type: application/json

{
  "nombre": "Consulta General Actualizada",
  "descripcion": "Servicio actualizado",
  "duracion": 30,
  "precio": 400.00,
  "disponible": true
}

### Actualizar disponibilidad

PUT http://localhost:3000/servicios/c8fd3bdd-a690-4a9c-90ae-671563cd84d0/disponibilidad
Content-Type: application/json

{
  "disponible": false
}

### Eliminar un servicio
DELETE http://localhost:3000/servicios/c8fd3bdd-a690-4a9c-90ae-671563cd84d0

###Citas