###Autenticacion 

###Registro de Usuario
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Erick Mendez",
  "email": "emendeza@unah.hn",
  "phone": "33333333",
  "role": "admin"
}

###Inicio de Sesión
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "user":"emendeza@unah.hn",
  "password":"ErickMendez123#"
}

###Registro de Usuario
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "user":"easl2991@gmail.com",
  "password":"ErickMendez123#"
}

###Actualizar Contraseña
PATCH http://localhost:3000/api/auth/set-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI1ZDIzZGI1LTkyYTgtNGI0Yi1hY2E4LTNkYjAxYTA2MDQxYiIsInBhc3N3b3JkX2hhc2giOiIkMmIkMTAkejlidjloSk5OS2F2OElxWk1zZGZ6LmxPclpPSUtBRnFGdUZVaDNLSkVGVmc5YTVHRUR6SnUiLCJtdXN0Q2hhbmdlUGFzc3dvcmQiOnRydWUsImlhdCI6MTc1NDI2MDg2MSwiZXhwIjoxNzU0MjY0NDYxfQ.2q4GGpuaL8NRPGedf1rbzeCUi_aoRekP4PcLwaxViyk

{ 
 "old_password":"-jyl}2nzQa5P",
 "new_password":"ErickMendez123#", 
 "confirm_password": "ErickMendez123#"
}

### Mostrar todos los usuarios
GET http://localhost:3000/api/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI1ZDIzZGI1LTkyYTgtNGI0Yi1hY2E4LTNkYjAxYTA2MDQxYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NDcwOTUyNywiZXhwIjoxNzU0NzUyNzI3fQ.Rl0hI2NCjU7nKjpNKvSCC0jQKpXQXIxLu-bZSGVrcTo

### Mostrar usuarios por rol
GET http://localhost:3000/api/auth/users/role?role=client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI1ZDIzZGI1LTkyYTgtNGI0Yi1hY2E4LTNkYjAxYTA2MDQxYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NDcwOTUyNywiZXhwIjoxNzU0NzUyNzI3fQ.Rl0hI2NCjU7nKjpNKvSCC0jQKpXQXIxLu-bZSGVrcTo



###Servicios 

### Consulta de todos los servicios
GET http://localhost:3000/api/servicios

### Consulta de servicios disponibles
GET http://localhost:3000/api/servicios/disponibilidad?available=true

### Crear un servicio
POST http://localhost:3000/api/servicios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEzODkxYzQ4LTM1OGYtNDdlMC05NzRjLWQ3OTU1OWJmMGZkOSIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NTQ2NDI1MjEsImV4cCI6MTc1NDY4NTcyMX0.3W_MhwiWbiA4oq-vHTNfC1f4BIoyLTjo0Wx27kKZMpw

{
  "nombre": "Consulta General",
  "descripcion": "Servicio de consulta medica general",
  "duracion": 30,
  "precio": 500.00,
  "disponible": true
}

### Crear un servicio
POST http://localhost:3000/api/servicios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI1ZDIzZGI1LTkyYTgtNGI0Yi1hY2E4LTNkYjAxYTA2MDQxYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NDY0MTk5MCwiZXhwIjoxNzU0Njg1MTkwfQ.LCCkE2_gb-LTpVZWxofxNcskUG1J-TZU7zMPvZFVZmA

{
  "nombre": "Cirugía",
  "descripcion": "Servicio de cirugía general",
  "duracion": 120,
  "precio": 15000.00,
  "disponible": true
}

### Actualizar un servicio
PUT http://localhost:3000/api/servicios/c8fd3bdd-a690-4a9c-90ae-671563cd84d0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI1ZDIzZGI1LTkyYTgtNGI0Yi1hY2E4LTNkYjAxYTA2MDQxYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NDY0MTk5MCwiZXhwIjoxNzU0Njg1MTkwfQ.LCCkE2_gb-LTpVZWxofxNcskUG1J-TZU7zMPvZFVZmA

{
  "nombre": "Consulta General Actualizada",
  "descripcion": "Servicio actualizado",
  "duracion": 30,
  "precio": 400.00,
  "disponible": true
}

### Actualizar disponibilidad

PUT http://localhost:3000/api/servicios/c8fd3bdd-a690-4a9c-90ae-671563cd84d0/disponibilidad
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI1ZDIzZGI1LTkyYTgtNGI0Yi1hY2E4LTNkYjAxYTA2MDQxYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NDY0MTk5MCwiZXhwIjoxNzU0Njg1MTkwfQ.LCCkE2_gb-LTpVZWxofxNcskUG1J-TZU7zMPvZFVZmA

{
  "disponible": false
}

### Eliminar un servicio
DELETE http://localhost:3000/api/servicios/c8fd3bdd-a690-4a9c-90ae-671563cd84d0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI1ZDIzZGI1LTkyYTgtNGI0Yi1hY2E4LTNkYjAxYTA2MDQxYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NDY0MTk5MCwiZXhwIjoxNzU0Njg1MTkwfQ.LCCkE2_gb-LTpVZWxofxNcskUG1J-TZU7zMPvZFVZmA
