# docker-compose.yml
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: clinic_project
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: clinica123
      MYSQL_DATABASE: dbClinica
      MYSQL_USER: clinicaUser
      MYSQL_PASSWORD: clinica123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    
volumes:
  mysql_data:
